Expose HTMLMediaElement.srcObject
scala-js/scala-js-dom pull request #365
Opened 2019-05-13 22:42 UTC by exoego

Closes #253.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/srcObject),
`srcObject` was able to be a MediaStream, a MediaSource, a Blob, or a File.
But as of November 2017, browsers only support MediaStream.
So it should be in this type facade.

2019-05-14 08:20 UTC, sjrd commented on src/main/scala/org/scalajs/dom/raw/Html.scala
> +  var srcObject: org.scalajs.dom.experimental.mediastream.MediaStream
Hum, even if browsers only support `MediaStream` at the moment, I believe we should use `MediaStream | MediaSource | Blob`, which is the standardized IDL type. That's because a `var` can also be *read*, and when one reads it in a future version of a browser, it could return one of the two other types.

2019-05-14 08:21 UTC, sjrd commented on src/main/scala/org/scalajs/dom/raw/Html.scala
> +  var srcObject: org.scalajs.dom.experimental.mediastream.MediaStream
Also, the IDL specifies `srcObject` as optional, so it should be a `js.UndefOr[MediaStream | MediaSource | Blob]`, actually.

2019-05-16 09:47 UTC, exoego commented on src/main/scala/org/scalajs/dom/raw/Html.scala
> +  var srcObject: org.scalajs.dom.experimental.mediastream.MediaStream
Fixed in https://github.com/scala-js/scala-js-dom/pull/365/commits/b43af8dcf87a12da2bc9950192d584b874589636

2019-06-13 23:15 UTC, exoego commented
Travis issue may be fixed in #368

2019-06-14 07:52 UTC, sjrd commented
#368 was merged. Could you rebase this PR?

2020-02-05 03:08 UTC, exoego commented
@sjrd 
Sorry for long absense.
I rebased and fixed formatting.
All CI jobs passed except this one: https://travis-ci.org/scala-js/scala-js-dom/jobs/646237220#L245
Could you restart only this job ?

2020-03-25 11:06 UTC, sjrd commented on src/main/scala/org/scalajs/dom/raw/Html.scala
> +      dom.experimental.mediastream.MediaStream | dom.experimental.mediastream.MediaSource | Blob]
Consider
```scala
import dom.experimental.mediastream.{MediaStream, MediaSource}
```
at the top so that you can just write
```suggestion
  var srcObject: js.UndefOr[MediaStream | MediaSource | Blob]
```

2020-03-25 11:16 UTC, sjrd commented on src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
> +  def sourceBueffers: SourceBufferList = js.native
```suggestion
  def sourceBuffers: SourceBufferList = js.native
```

2020-03-25 11:17 UTC, sjrd commented on src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
> +  def endOfStream(error: js.UndefOr[EndOfStreamError] = ???): Unit = js.native
```suggestion
  def endOfStream(error: EndOfStreamError = js.native): Unit = js.native
```
better matches the IDL definition.

2020-03-25 11:23 UTC, sjrd commented on src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
> +@js.native
Please add a blank line between traits/classes/objects. Same below.

2020-06-20 11:56 UTC, exoego commented on src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
> +  def endOfStream(error: js.UndefOr[EndOfStreamError] = ???): Unit = js.native
Fixed in https://github.com/scala-js/scala-js-dom/pull/365/commits/f810f35f7005100bb590814cbfd4d248d4da5329

2020-06-20 11:56 UTC, exoego commented on src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
> +@js.native
Fixed in https://github.com/scala-js/scala-js-dom/pull/365/commits/4dcd3d6ab9c54f1addd9a0cfdfc52de99fe5d513

2020-06-20 11:56 UTC, exoego commented on src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
> +  def sourceBueffers: SourceBufferList = js.native
Fixed in https://github.com/scala-js/scala-js-dom/pull/365/commits/328db8dedd4adfa634498ac84b364c8645ba30bb

2020-06-20 11:56 UTC, exoego commented on src/main/scala/org/scalajs/dom/raw/Html.scala
> +      dom.experimental.mediastream.MediaStream | dom.experimental.mediastream.MediaSource | Blob]
Fixed in https://github.com/scala-js/scala-js-dom/pull/365/commits/053820ea6cc16097476e13349b43bee6fc910f47

2021-08-08 11:40 UTC, armanbilge approved these changes

2021-08-08 11:42 UTC, armanbilge commented
Also assuming an [implicit approval](https://github.com/scala-js/scala-js-dom/pull/365#pullrequestreview-381048020) from @sjrd ;) 

> I just have a few small suggestions, then it's good to go.

2021-08-09 10:02 UTC, exoego commented
I am OK having this only on v2.

2021-08-13 00:08 UTC, japgolly commented
> I am OK having this only on v2.

I think there's no reason not to add this to 1.2.0 as well cos you're just adding new stuff. Our goal for 1.2.0 is to get as much in as we can without breaking bin-compat.

2021-08-13 01:34 UTC, japgolly requested changes

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/SourceBuffer[JT] var timestampOffset: Double
Missing `trackDefaults`

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/SourceBufferList[JT] @JSBracketAccess def apply(index: Double): SourceBuffer
s/Double/Int/

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/SourceBufferList[JT] def length: Double
s/Double/Int/

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/AudioTrackList[JT] def length: Double
s/Double/Int/

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrack[JT] def activeCues: js.UndefOr[TextTrackCueList]
I don't see in the doc anything to indicate this can be `undefined`.

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrack[JT] def cues: js.UndefOr[TextTrackCueList]
I don't see in the doc anything to indicate this can be `undefined`.

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrackCue[JT] def track: js.UndefOr[TextTrack]
`| Null`, not `UndefOr`

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrackCueList[JT] @JSBracketAccess def apply(index: Double): TextTrackCue
Should be Int... or are you using Double cos we don't have native longs?

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrackCueList[JT] def length: Double
Should be Int... or are you using Double cos we don't have native longs?

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrackCueList[JT] def getCueById(id: String): js.UndefOr[TextTrackCue]
Null, not UndefOr

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrackList[JT] @JSBracketAccess def apply(index: Double): VideoTrack
Int

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrackList[JT] def length: Double
Int

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrackList[JT] def getTrackById(id: String): js.UndefOr[TextTrack]
Null

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/VideoTrackList[JT] @JSBracketAccess def apply(index: Double): VideoTrack
Int

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/VideoTrackList[JT] def getTrackById(id: String): js.UndefOr[VideoTrack]
Null

2021-08-13 01:34 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/VideoTrackList[JT] def length: Double
Int

2021-08-13 02:07 UTC, armanbilge commented on api-reports/2_12.txt
> +experimental/mediastream/AudioTrackList[JT] def getTrackById(id: String): js.UndefOr[AudioTrack]
Maybe #481 should target 2.x, and for now let's keep things consistent in the 1.x series (i.e., no `X | Null`)?

2021-08-13 05:18 UTC, exoego commented on api-reports/2_12.txt
> +experimental/mediastream/AudioTrackList[JT] @JSBracketAccess def apply(index: Double): AudioTrack
According to https://html.spec.whatwg.org/multipage/media.html#videotracklist it is `unsigned long`, so I think `Double` is more appropriate.
```
readonly attribute unsigned long length;
getter VideoTrack (unsigned long index);
VideoTrack? getTrackById(DOMString id);
readonly attribute long selectedIndex;
```

2021-08-13 05:35 UTC, sjrd commented on api-reports/2_12.txt
> +experimental/mediastream/VideoTrackList[JT] def length: Double
If it says `long` or `unsigned long` in the IDL, it must be `Double` in Scala.js. Otherwise it won't be able to represent values that don't fit in an Int.

I'm not saying this is the case here. It's just a general comment since I've seen many suggestions like this change, and I'm guessing that some of them might not take the above rule into account.

2021-08-13 05:36 UTC, exoego commented on api-reports/2_12.txt
> +experimental/mediastream/SourceBufferList[JT] @JSBracketAccess def apply(index: Double): SourceBuffer
Is `Int` OK ?
https://w3c.github.io/media-source/#sourcebufferlist says `unsigned long`.

2021-08-13 05:36 UTC, exoego commented on api-reports/2_12.txt
> +experimental/mediastream/SourceBufferList[JT] def length: Double
Is `Int` OK ?
https://w3c.github.io/media-source/#sourcebufferlist says `unsigned long`.

2021-08-13 05:39 UTC, exoego commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrack[JT] def activeCues: js.UndefOr[TextTrackCueList]
https://html.spec.whatwg.org/multipage/media.html#texttrack
```
readonly attribute TextTrackCueList? cues;
readonly attribute TextTrackCueList? activeCues;
```

I think `TextTrackCueList?` corresponds to `js.UndefOr[...]`

2021-08-13 05:39 UTC, exoego commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrack[JT] def cues: js.UndefOr[TextTrackCueList]
Same https://github.com/scala-js/scala-js-dom/pull/365/files#r688256324

2021-08-20 00:12 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/AudioTrack[JT] var enabled: Boolean
Actually this is in the extensions draft, not the original spec

2021-08-20 00:15 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/SourceBuffer[JT] var timestampOffset: Double
Actually `trackDefaults` is deprecated and non-standard

2021-08-20 00:18 UTC, japgolly commented on api-reports/2_12.txt
> +experimental/mediastream/TextTrack[JT] def activeCues: js.UndefOr[TextTrackCueList]
Yeah I wasn't sure either but just read through the spec and `T?` is `T | null`.
See https://heycam.github.io/webidl/#idl-nullable-type

@armanbilge FYI ↑

2021-08-20 00:26 UTC, japgolly commented
@armanbilge This is ready to go, please merge if you're happy

2021-08-20 00:30 UTC, armanbilge approved these changes

2021-08-20 00:30 UTC, merged