IDBVersionChangeEvent.newVersion can be null
scala-js/scala-js-dom pull request #429
Opened 2020-11-13 06:19 UTC by japgolly

2020-11-13 06:20 UTC, japgolly commented
Spec: https://www.w3.org/TR/IndexedDB/#events

2020-11-13 10:59 UTC, sjrd requested changes
Thanks for the PR.

2020-11-13 10:59 UTC, sjrd commented on src/main/scala/org/scalajs/dom/raw/Idb.scala
> +  var newVersion: js.UndefOr[Int | Null] = js.undefined
The convention so far has been to use the boxed classes when we have primitive-or-null. So this should be
```suggestion
  var newVersion: js.UndefOr[Integer] = js.undefined
```
In a future where Scala has explicit nulls, that will change. But we're not there yet.

2020-11-13 10:59 UTC, sjrd commented on src/main/scala/org/scalajs/dom/raw/Idb.scala
> +  def newVersion: Int | Null = js.native
```suggestion
  def newVersion: Integer = js.native
```

2020-11-14 00:13 UTC, japgolly commented on src/main/scala/org/scalajs/dom/raw/Idb.scala
> +  var newVersion: js.UndefOr[Int | Null] = js.undefined
Np. Updated.

2021-08-20 02:23 UTC, armanbilge approved these changes

2021-08-20 02:23 UTC, merged