Support scala 3.0.0-RC1
scala-js/scala-js-dom pull request #446
Opened 2021-02-26 19:54 UTC by russwyte

Add support for Scala 3.0.0-RC1 in anticipation of final release of Scala 3.0.0

2021-02-26 20:57 UTC, DanHodges approved these changes

2021-02-26 20:58 UTC, DanHodges approved these changes

2021-03-01 21:51 UTC, Taig commented on src/main/scala/org/scalajs/dom/experimental/sharedworkers/SharedWorker.scala
> -class SharedWorker(stringUrl: String, name: js.UndefOr[String] = js.native)
As I was facing the same problem recently, you could overload the constructor:
```scala
class SharedWorker(stringUrl: String, name: js.UndefOr[String])
    extends webworkers.AbstractWorker {
  def this(stringUrl: String) = this(stringUrl, js.native)
```

2021-03-02 16:22 UTC, russwyte commented on src/main/scala/org/scalajs/dom/experimental/sharedworkers/SharedWorker.scala
> -class SharedWorker(stringUrl: String, name: js.UndefOr[String] = js.native)
I see - maybe this would be better as an `apply` on the companion object?

2021-03-02 16:36 UTC, sjrd commented on src/main/scala/org/scalajs/dom/experimental/sharedworkers/SharedWorker.scala
> -class SharedWorker(stringUrl: String, name: js.UndefOr[String] = js.native)
If must be constructor overloading. It needs to mirror the JS API.

2021-03-02 16:37 UTC, russwyte commented on src/main/scala/org/scalajs/dom/experimental/sharedworkers/SharedWorker.scala
> -class SharedWorker(stringUrl: String, name: js.UndefOr[String] = js.native)
OK - I will make that adjustment. Thanks for the feedback.

2021-03-02 17:57 UTC, vhiairrassary commented
@russwyte What do you think about adding the newly supported version in [CI pipeline](https://github.com/scala-js/scala-js-dom/blob/master/.travis.yml#L6)?

2021-03-02 18:07 UTC, russwyte commented
Travis CI seems super slow for this. It may be time to consider moving to github actions.

2021-03-03 13:55 UTC, sjrd commented on .github/workflows/ci.yml
> +        scalaversion: ["2.11.12", "2.12.10", "2.13.1", "2.13.5", "3.0.0-RC1"]
Don't include 2.13.5. It won't work with 0.6.x, and we only need one 2.13.x version. 2.13.1 is there and works.
```suggestion
        scalaversion: ["2.11.12", "2.12.10", "2.13.1", "3.0.0-RC1"]
```

2021-03-03 13:55 UTC, sjrd commented on build.sbt
> +  if (scalaJSVersion.startsWith("1.")) Seq("2.12.10", "2.11.12", "2.13.5", "3.0.0-RC1")
Same here; keep 2.13.1.
```suggestion
  if (scalaJSVersion.startsWith("1.")) Seq("2.12.10", "2.11.12", "2.13.1", "3.0.0-RC1")
```

2021-03-03 13:55 UTC, sjrd commented on src/main/scala/org/scalajs/dom/experimental/URL.scala
> +  def this(url: String) = this(url, js.native)
Why is this necessary? If the original code is not accepted by Scala 3, please report an issue to the dotty repo, because that's a bug.

2021-03-03 13:55 UTC, sjrd commented on build.sbt
> +  resolvers += Resolver.JCenterRepository,
This should not be necessary with Scala 3.0.0-RC1 and following.

2021-03-03 14:18 UTC, russwyte commented on src/main/scala/org/scalajs/dom/experimental/URL.scala
> +  def this(url: String) = this(url, js.native)
Yeah the original would not compile in 3.0.0-RC1 - I will report.

2021-03-03 14:30 UTC, russwyte commented on build.sbt
> +  resolvers += Resolver.JCenterRepository,
It looks like it may still be required?
```
Run sbt "++3.0.0-RC1" doc
[info] welcome to sbt 1.5.0-M2 (AdoptOpenJDK Java 1.8.0_275)
[info] loading settings for project scala-js-dom-build from build.sbt ...
[info] loading project definition from /home/runner/work/scala-js-dom/scala-js-dom/project
[info] loading settings for project root from build.sbt ...
[info] set current project to Scala.js DOM (in build file:/home/runner/work/scala-js-dom/scala-js-dom/)
[info] Setting Scala version to 3.0.0-RC1 on 2 projects.
[info] Excluded 1 projects, run ++ 3.0.0-RC1 -v for more details.
[info] Reapplying settings...
[info] set current project to Scala.js DOM (in build file:/home/runner/work/scala-js-dom/scala-js-dom/)
[info] compiling 53 Scala sources to /home/runner/work/scala-js-dom/scala-js-dom/target/scala-3.0.0-RC1/classes ...
[info] done compiling
[error] Unresolved scala3doc artifact
[error] add 'ThisBuild / resolvers += Resolver.JCenterRepository'
```

2021-03-03 14:53 UTC, sjrd commented on build.sbt
> +  resolvers += Resolver.JCenterRepository,
OK, let's keep it for now, then. :s

2021-03-03 16:23 UTC, russwyte commented
@sjrd I am a bit stumped as to why this won't compile for 2.10.7/0.6.x:
```
[info] set current project to Scala.js DOM (in build file:/home/runner/work/scala-js-dom/scala-js-dom/)
[info] Setting Scala version to 2.10.7 on 2 projects.
[info] Excluded 1 projects, run ++ 2.10.7 -v for more details.
[info] Reapplying settings...
[info] set current project to Scala.js DOM (in build file:/home/runner/work/scala-js-dom/scala-js-dom/)
[info] compiling 53 Scala sources to /home/runner/work/scala-js-dom/scala-js-dom/target/scala-2.10/classes ...
[error] /home/runner/work/scala-js-dom/scala-js-dom/src/main/scala/org/scalajs/dom/experimental/beacon/package.scala:44:70: js.native may only be used as stub implementation in facade types
[error]     def sendBeacon(url: String, data: BodyInit = null): Boolean = js.native
...
```

2021-03-03 16:27 UTC, sjrd commented
It does seem weird. Can you reproduce the issue locally?

2021-03-03 16:40 UTC, russwyte commented on src/main/scala/org/scalajs/dom/experimental/URL.scala
> +  def this(url: String) = this(url, js.native)
Created:
https://github.com/lampepfl/dotty/issues/11592

2021-03-03 16:53 UTC, russwyte commented
> It does seem weird. Can you reproduce the issue locally?

yes - running:

```
 SCALAJS_VERSION="0.6.28" sbt "++2.10.7" example/compile
 ```
 
fails.

2021-03-03 17:56 UTC, russwyte commented
@sjrd The compiler error seems to be an issue with order of build tasks and incremental compiling. 

I added a clean to the problematic step `example/compile` and it cleared up the CI build.

2021-04-01 21:41 UTC, russwyte commented
@sjrd  It looks like DottyDoc does not like some of our overloaded constructors. That has me stuck.

2021-04-25 00:54 UTC, raquo commented
Does anyone know if the blockers have been addressed in RC3?

2021-04-25 12:28 UTC, russwyte commented
> 
> 
> Does anyone know if the blockers have been addressed in RC3?

I tried RC3 a few days ago and unfortunately the DottyDoc issue still persists. Everything else is working.

2021-04-25 14:38 UTC, sjrd commented
It would be nice if someone could minimize and report the issue to the dotty repo.

2021-04-25 15:56 UTC, russwyte commented
> It would be nice if someone could minimize and report the issue to the dotty repo.

https://github.com/lampepfl/dotty/issues/12215

2021-06-03 14:45 UTC, russwyte commented
@sjrd that last commit got scaladocs working for Scala 3. Please let me know if more is needed.

2021-07-01 04:44 UTC, armanbilge commented
@russwyte @sjrd What will it take to get this merged? Happy to pitch in a hand :) we'd love this over at https://github.com/http4s/http4s/pull/4938

2021-07-06 18:14 UTC, armanbilge commented
@sjrd @gzm0 just a polite bump. I understand if you are busy to review, but at the very least could you kindly approve the workflow, so we can see how this PR stands against CI?

2021-07-06 20:08 UTC, sjrd commented
There's nothing that I can approve. It just says "Workflow completed with no jobs." 🤔😕

2021-07-06 20:36 UTC, armanbilge commented
@sjrd thanks for your attention ... that's strange. I tried re-opening in https://github.com/scala-js/scala-js-dom/pull/449, can you approve there?

2021-07-06 22:29 UTC, sjrd commented
Done

2021-07-06 22:44 UTC, armanbilge commented
Thank you very much! I'll continue working on the PR there.

2021-07-06 23:06 UTC, armanbilge commented on .github/workflows/ci.yml
> +          - scalaversion: "3.0.1-RC2"
Why bump to a RC? let's first get this released for 3.0.0 😅

2021-07-06 23:13 UTC, russwyte commented on .github/workflows/ci.yml
> +          - scalaversion: "3.0.1-RC2"
Already tried 3.0.0 (earlier) didn't work becuase work because of sbt and scaladoc/dottydoc borkage with scalajs. But if it can work now (maybe SBT fix?) - that's great! 👍 

3.0.1-RC1 and on will work right now.

2021-07-06 23:24 UTC, armanbilge commented on .github/workflows/ci.yml
> +          - scalaversion: "3.0.1-RC2"
I see! Frustrating. Btw thanks for picking this up again!

PS if you make a tiny PR to this repo (e.g. fix a typo) maybe @sjrd can merge it quick and then you'll be whitelisted for CI.

2021-07-07 00:12 UTC, russwyte commented on .github/workflows/ci.yml
> +          - scalaversion: "3.0.1-RC2"
I don't mind doing a PR like that, but what is strange is that until a few commits ago CI was working fine.

2021-07-07 00:17 UTC, armanbilge commented on .github/workflows/ci.yml
> +          - scalaversion: "3.0.1-RC2"
GH changed their policy recently, maybe while you were working on this. It makes contributing more difficult IMO.

2021-07-09 13:26 UTC, armanbilge commented
@russwyte @sjrd Scala 3.0.1 was [just released](https://github.com/lampepfl/dotty/releases/tag/3.0.1) and CI is green. So, what will it take to merge? :)

2021-07-14 06:00 UTC, armanbilge commented
@sjrd another polite bump. At least let's run the workflow, please?

2021-07-14 07:54 UTC, Myp commented
@sjrd I agree with @armanbilge :) let's rock please!

2021-07-14 07:55 UTC, sjrd requested changes
Thanks for the continued efforts.

I have some comments below. In addition, could you squash/rebase everything in 3 commits with appropriate commit messages:
1. Upgrade sbt and change the syntax
2. Upgrade Scala.js to 1.5.0
3. Add the support for Scala 3, and all the other changes.

2021-07-14 07:55 UTC, sjrd commented on .github/workflows/ci.yml
> +        run: sbt "++${{ matrix.scalaversion }} clean;example/compile"
Those changes shouldn't be necessary.

2021-07-14 07:55 UTC, sjrd commented on build.sbt
> +  (Compile / resources) += (example / Compile / fullOptJS).value.data,
When rebasing, can you isolate those changes of build syntax in a first commit, together with the upgrade of sbt, please?

2021-07-14 07:55 UTC, sjrd commented on src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
> +import scala.scalajs.js.{undefined, |}
Spurious changes that should be reverted.

2021-07-14 07:55 UTC, sjrd commented on src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
> +    this(typeArg = "datachannel", init = init)
Does this change have anything to do with the support for Scala 3?

2021-07-14 07:55 UTC, sjrd commented on src/main/scala/org/scalajs/dom/ext/package.scala
> -
Please keep this empty line. We always keep `import scala.language.*` separate from the others.

2021-07-14 07:55 UTC, sjrd commented on src/main/scala/org/scalajs/dom/raw/lib.scala
> +//  def this(typeArg: String) = this(typeArg, js.native)
Do these changes have anything to do with Scala 3 support?

2021-07-14 11:54 UTC, armanbilge commented
@sjrd I rebased and fixed according to your comments in #450. I hope that adding @russwyte to the rebased commits as a co-author is consistent with your coding style; please advise.

2021-07-14 13:54 UTC, sjrd commented
Superseded by #450.

2021-07-14 13:54 UTC, closed without merging