Document coding standards and conventions
scala-js/scala-js-dom pull request #523
Opened 2021-08-30 01:52 UTC by japgolly

Closes #519

Pending #514

2021-08-30 01:53 UTC, japgolly commented
@armanbilge @lihaoyi @sjrd Would you all mind having a review of this?

2021-08-30 08:32 UTC, sjrd commented on CONTRIBUTING.md
> +========
I haven't made up a clear mind about this, but IMO the default should be to put everything inside `dom`, under their normal DOM name. The DOM is not namespaced itself, so it probably does not make sense to namespace things in scalajs-dom, especially for API subsets with a small surface.

Potential exceptions could be made for very large subspecifications. Currently, I can think of WebGL and Intl as the two most likely candidates for specific packages.

2021-08-30 08:32 UTC, sjrd commented on CONTRIBUTING.md
> +  available (subjective judgement here) in the `ext` package.
In my vision, the ideal outcome would be that we don't have anything left that belongs to this category, and hence that the `ext` package disappears. But that's only IMO.

2021-08-30 08:32 UTC, sjrd commented on CONTRIBUTING.md
> +Binary compatibility for Scala.JS facades is different than standard Scala.
```suggestion
Binary compatibility for Scala.js facades is different than standard Scala.
```

2021-09-01 00:53 UTC, armanbilge commented on CONTRIBUTING.md
> +========
> The DOM is not namespaced itself, so it probably does not make sense to namespace things in scalajs-dom

Thinking towards an auto-generated future, this is also good. Since generators wouldn't know about our namespaces without manual interventions.

2021-09-01 00:53 UTC, armanbilge commented on CONTRIBUTING.md
> +  This is effectively Java-style.
👍

2021-09-01 00:53 UTC, armanbilge commented on CONTRIBUTING.md
> +  available (subjective judgement here) in the `ext` package.
Agree, but what to do with the things currently in there? 🤔

2021-09-01 00:53 UTC, armanbilge commented on CONTRIBUTING.md
> +   (see above). We'll probably automate this step in the future (See #503)
I think in the section above we should include some examples of what compatible/incompatible changes look like in the API reports. Specifically what all the `[ST]` and `[JT]` etc. means, I know they are documented at the top of the reports but nobody will see that when they check the diff.

2021-09-01 00:53 UTC, armanbilge commented on CONTRIBUTING.md
> +  * put all of its types in its package
We should mention, if you are adding something this large/significant probably good to raise an issue for any necessary discussion before doing all this work!

2021-09-01 03:38 UTC, sjrd commented on CONTRIBUTING.md
> +  available (subjective judgement here) in the `ext` package.
In my cleanup PR I am moving, deprecating, or outright removing everything in `ext`, so there's nothing left there if it gets accepted.

2021-09-01 03:40 UTC, armanbilge commented on CONTRIBUTING.md
> +  available (subjective judgement here) in the `ext` package.
Apologies, it's been too long since I reviewed it and I was much less familiar with the library then.

2021-09-03 00:22 UTC, japgolly commented on CONTRIBUTING.md
> +  available (subjective judgement here) in the `ext` package.
Yep now that #458 is merged everything in `ext` is deprecated. *chef's kiss*

2021-09-03 00:23 UTC, japgolly commented on CONTRIBUTING.md
> +Binary compatibility for Scala.JS facades is different than standard Scala.
Noted. Committing to my long-term RAM...

2021-09-03 00:35 UTC, japgolly commented on CONTRIBUTING.md
> +========
I've raised #545 to follow this thread.

2021-09-03 00:49 UTC, japgolly commented
Addressed PR feedback. Just need to sort out packages in #545

2021-09-04 22:21 UTC, japgolly commented
Ok this should be good to go now, @armanbilge can you please give this a final review and hopefully a merge :)

2021-09-04 22:50 UTC, armanbilge commented on CONTRIBUTING.md
> +  This is effectively Java-style.
This is pending #476, unless we grandparent in all existing files but enforce for new files. Also, without namespaces this could get messy. Or not.

2021-09-04 22:55 UTC, armanbilge commented on CONTRIBUTING.md
> +  * put it all in `dom`
We can remove all of this now right? I assume we're not even doing the companion-object thing, because that's also a form of namespacing.

2021-09-04 22:56 UTC, armanbilge commented on CONTRIBUTING.md
> +  * put it all in `dom`
Oh, this is where the `def` / `val` thing can go.

2021-09-04 22:59 UTC, armanbilge commented on CONTRIBUTING.md
> +
We can just drop this section. Let's add an intro section to this that says we accept PRs for anything in the spec.

2021-09-04 23:00 UTC, armanbilge commented on CONTRIBUTING.md
> +   (see above). We'll probably automate this step in the future (See #503)
Did I miss where you added this?

2021-09-04 23:02 UTC, armanbilge requested changes
Sorry, this is a moving target with all the other changes/decisions going on 🎯 I'll write up a friendly intro to add to this :)

2021-09-04 23:06 UTC, armanbilge commented on CONTRIBUTING.md
> +   entire API. Make sure to look at the top of the file for a description of format.
Oh, I see this now. Hmm, I still think some examples would be helpful. Anyway, let's not block on this and I'll do it in a follow-up PR, sound good? :)

2021-09-04 23:11 UTC, japgolly commented on CONTRIBUTING.md
> +   entire API. Make sure to look at the top of the file for a description of format.
Yeah great! Thank you!

2021-09-04 23:11 UTC, japgolly commented on CONTRIBUTING.md
> +
Yeah great idea. Can I leave this to you then in your follow up PR? Or else I can come back to this tomorrow

2021-09-04 23:11 UTC, japgolly commented on CONTRIBUTING.md
> +  This is effectively Java-style.
Nah I reckon let's just state it now and we'll do #476 next. wdyt?

2021-09-04 23:12 UTC, armanbilge commented on CONTRIBUTING.md
> +
Oh yeah, that's fine I'll do it in the follow-up. If you address everything else we can merge!

2021-09-04 23:14 UTC, armanbilge commented on CONTRIBUTING.md
> +  This is effectively Java-style.
Ok, so we're going ahead with #476? I wasn't sure because https://github.com/scala-js/scala-js-dom/issues/545#issuecomment-912187479.

2021-09-05 00:44 UTC, armanbilge commented
Add intro, api report ex, other fixes

2021-09-05 00:51 UTC, armanbilge approved these changes
@japgolly I pushed my changes here. Apologies, for expediency I'm going to merge pro-actively (hope it's okay) so that I can make a call for PRs and point to this guide. Please review when you next have a chance!

2021-09-05 00:52 UTC, merged

2021-09-05 00:57 UTC, armanbilge commented on CONTRIBUTING.md
> +The majority of useful changes to scala-js-dom are indeed binary compatible.
I'm afraid this section just creates confusion esp. since most changes really are binary compatible anyway. IDK if we should put this burden on users. It's fine to have a section like "if you're interested" but asking that they understand this to make a PR might be intimidating.

2021-09-05 01:23 UTC, japgolly commented
Fantastic additions!! Very nice!!