The great migration to `dom`
scala-js/scala-js-dom pull request #588
Opened 2021-09-27 22:13 UTC by armanbilge

Trying to wrap up #545.

2021-09-28 02:46 UTC, armanbilge commented
Phew 😅 that's the whole lot. I'd be shocked if this is 100% perfect, but if any issues do come up we should be able to fix them binary-compatibly.

2021-09-28 08:52 UTC, sjrd commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
You can cheat:

1. Make `package object crypto` an `object crypto` instead.
2. Declare `subtle` and `getRandomValues()` as `@js.native val/def`s members of the `object crypto`, with `@JSGlobal("crypto.subtle")` and `@JSGlobal("crypto.getRandomValues")`.
3. Remove this `webCrypto`

2021-09-28 08:54 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
Nice! Thanks!

2021-09-28 22:25 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
@sjrd Hmm, I'm getting this warning:
```
Generated class org.scalajs.dom.crypto differs only in case from org.scalajs.dom.Crypto (defined in Crypto.scala).
  Such classes will overwrite one another on case-insensitive filesystems
```
Is this something to be concerned about and/or is there a workaround?

2021-09-28 22:27 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
Maybe if we rename the object to e.g. `webcrypto` and then inside the `dom` package object we put `val crypto = webcrypto`?

2021-09-28 22:55 UTC, sjrd commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
Hum... Remove `Crypto`? It's not like there's any use case for it anyway.

Or turn `crypto` back into a package object.

2021-09-28 22:57 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
I think we still need `Crypto` for source compatibility. So back to a package object then.

2021-09-29 03:18 UTC, sjrd commented on src/main/scala/org/scalajs/dom/crypto/package.scala
> +  @JSGlobal("crypto.subtle")
```suggestion
  @JSGlobal("crypto.getRandomValues")
```

2021-09-29 03:20 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/crypto/package.scala
> +  @JSGlobal("crypto.subtle")
My bad, thanks!

2021-09-29 03:21 UTC, sjrd commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
You don't need `Crypto` in `dom` for compatibility. You only need it in `crypto`. In `dom` you could either not have it at all, or have it under a different name, like `WebCrypto`. It's more important for `crypto` to have its original name because it is the common use case. `Crypto` is way less important.

2021-09-29 03:36 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
Ah, you're right. Although there's an argument to be made for migration ("change imports from `dom.crypto.*` to `dom.*` and It Just Works").

Is there anything suboptimal about using a `package object`?

2021-09-29 06:39 UTC, sjrd commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
Not per se. But it means that even in a later version where we can remove the deprecated things, we still won't be able to turn `crypto` into a regular native `val`.

To preserve imports, you could add a type alias
```scala
type Crypto = WebCrypto
```
as that won't generate a class file, and hence will not have any issue on case insensitive file systems.

2021-09-29 10:34 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
> we still won't be able to turn `crypto` into a regular native `val`.

Wait ... if `crypto` is an vanilla (not-package) `object`, we can make it a `val` binary-compatibly? I thought that removing objects would cause problems.

2021-09-29 10:57 UTC, sjrd commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
Not binary-compatibly, no. But source-compatibly, in a hypothetical scalajs-dom v3 one day.

2021-09-29 11:00 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
Right, thanks. Then I guess I'm confused why a `package object` can't become a native `val` source-compatibly?

2021-09-29 12:05 UTC, sjrd commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
It can, but you'll still be stuck by the `Crypto` trait.

2021-09-29 16:50 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
I'm sorry, I've completely lost the thread of discussion here 😕 in summary:
1. We currently have `Crypto` and `package object crypto`,
2. In SJS-dom v3 we can source-compatibly make this `Crypto` and `val crypto: Crypto = js.native`.

What's the problem?

2021-09-29 17:09 UTC, sjrd commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
Ah yes, you're completely right. I was confused.

So it's good as is. :)

2021-09-29 17:11 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  def webCrypto: Crypto = js.native
No worries! Thanks for all your help 😁

2021-10-12 02:46 UTC, japgolly requested changes
Few comments but fantastic work getting this done @armanbilge ! It would've involved quite a bit of tedium.

2021-10-12 02:46 UTC, japgolly commented on api-reports/2_13.txt
> +AudioTrackList[JT] var onremovetrack: js.Function1[Event, Any]
Can you confirm the above 5 lines? Types have changed and a new method appeared.

2021-10-12 02:46 UTC, japgolly commented on src/main/scala/org/scalajs/dom/MediaSource.scala
> +  def readyState: String = js.native
Looks like a mistake

2021-10-12 02:46 UTC, japgolly commented on src/main/scala/org/scalajs/dom/MediaSource.scala
> +  def endOfStream(error: String = js.native): Unit = js.native
Should be `EndOfStreamError` right?

2021-10-12 02:46 UTC, japgolly commented on src/main/scala/org/scalajs/dom/SourceBuffer.scala
> +  var mode: String = js.native
another seeming regression

2021-10-12 02:46 UTC, japgolly commented on src/main/scala/org/scalajs/dom/TextTrack.scala
> +  var mode: String = js.native
beep boop

2021-10-12 02:46 UTC, japgolly commented on src/main/scala/org/scalajs/dom/TextTrackList.scala
> +  var onremovetrack: js.Function1[Event, Any] = js.native
These look like the same events I commented on above. Can you confirm the types?

2021-10-12 02:46 UTC, japgolly commented on src/main/scala/org/scalajs/dom/WebGLRenderingContext.scala
> +  implicit class WebGLRenderingContextOps(val webGL: WebGLRenderingContext) extends AnyVal {
private val

2021-10-12 02:46 UTC, japgolly commented on src/main/scala/org/scalajs/dom/package.scala
> +  type Transferable = ArrayBuffer | MessagePort | CanvasProxy
erm? Pls confirm? Doesn't seem very migratory...

2021-10-12 02:46 UTC, japgolly commented on src/main/scala/org/scalajs/dom/crypto/GlobalCrypto.scala
> +@deprecated("use dom.crypto instead", "2.0.0")
This doesn't seem right. `dom.crypto` is now is the package object, where as this deprecated `dom.crypto.crypto` method returns an instance of `Crypto` which extends `js.Object`. 

Also because `crypto` isn't always available, shouldn't `dom.crypto` be an instance of `js.UndefOf[Crypto]`?

2021-10-12 02:50 UTC, armanbilge commented on api-reports/2_13.txt
> +AudioTrackList[JT] var onremovetrack: js.Function1[Event, Any]
That's because I merged duplicated facades.
https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/AudioTrackList.scala
https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/experimental/mediastream/AudioTrackList.scala

2021-10-12 02:53 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/MediaSource.scala
> +  def readyState: String = js.native
These were just straight aliases i.e. `type ReadyState = String` so I think I dropped these.
https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/experimental/mediastream/package.scala

What should happen, is these should be modeled as `sealed trait`s on Scala 2 and `opaque type` on Scala 3. Can that be a followup PR?

2021-10-12 02:53 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/MediaSource.scala
> +  def endOfStream(error: String = js.native): Unit = js.native
Same as above.

2021-10-12 02:53 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/SourceBuffer.scala
> +  var mode: String = js.native
Same as above (thanks for the careful eye btw :)

2021-10-12 02:53 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/TextTrack.scala
> +  var mode: String = js.native
same

2021-10-12 02:54 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/WebGLRenderingContext.scala
> +  implicit class WebGLRenderingContextOps(val webGL: WebGLRenderingContext) extends AnyVal {
```suggestion
  implicit class WebGLRenderingContextOps(private val webGL: WebGLRenderingContext) extends AnyVal {
```

2021-10-12 02:56 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  type Transferable = ArrayBuffer | MessagePort | CanvasProxy
I merged what was already there with
https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/experimental/serviceworkers/package.scala

2021-10-12 02:57 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/crypto/GlobalCrypto.scala
> +@deprecated("use dom.crypto instead", "2.0.0")
Yes, but to keep source compatibility we are in a bit of a hole. See my back-and-forth with @sjrd above.
https://github.com/scala-js/scala-js-dom/pull/588#discussion_r717154719

2021-10-12 02:58 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/crypto/GlobalCrypto.scala
> +@deprecated("use dom.crypto instead", "2.0.0")
In other words, this is source compatible. But, for anyone that specifically wanted a `Crypto` object (which I assume is rare) you're right this wouldn't work.

2021-10-12 02:59 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/MediaSource.scala
> +  def readyState: String = js.native
I guess I should fix that in this PR :)

2021-10-12 03:03 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/MediaSource.scala
> +  def readyState: String = js.native
Ah, I remember my concern. Since these are not officially declared types (are they?) I was concerned about namespace clashes. We need to be careful how we name them.

2021-10-12 03:07 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/MediaSource.scala
> +  def readyState: String = js.native
Compare with `BufferSource` which is officially declared: https://developer.mozilla.org/en-US/docs/Web/API/BufferSource

I guess what we should do is keep these for source compatibility, but deprecate them?

2021-10-13 18:22 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/TextTrack.scala
> +  var mode: String = js.native
Fixed! :)

2021-10-13 18:33 UTC, armanbilge commented on src/main/scala/org/scalajs/dom/package.scala
> +  type Transferable = ArrayBuffer | MessagePort | CanvasProxy
I can't find this page in English, but it confirms this.
https://developer.mozilla.org/de/docs/Web/API/Transferable

2021-10-17 06:50 UTC, japgolly commented on src/main/scala/org/scalajs/dom/MediaSource.scala
> +  def readyState: String = js.native
Nice re concept. That's a very good point you raise about namespace pollution. Following Typescript's lead is a great idea.

2021-10-17 06:53 UTC, japgolly commented on src/main/scala/org/scalajs/dom/crypto/GlobalCrypto.scala
> +@deprecated("use dom.crypto instead", "2.0.0")
> But, for anyone that specifically wanted a Crypto object (which I assume is rare) you're right this wouldn't work.

I rely on a `Crypto` object in my code :) Let me take a stab at a solution...

2021-10-17 07:12 UTC, japgolly requested changes
LGTM! Just two minor changes, and the `crypto` problem. Maybe we could merge with `crypto` as is and then I take a shot at it in a follow up PR?

2021-10-17 07:43 UTC, armanbilge commented
Thanks again for your careful eye! Fixed those `TrackEvent`s that slipped through and should be good to go when green.

2021-10-17 08:23 UTC, merged

2021-10-17 08:25 UTC, armanbilge commented
Actually this was made SO much easier after you split all the files! So much credit to you as well that was a life saver!!