Fetch request body as ReadableStream
scala-js/scala-js-dom pull request #628
Opened 2021-11-10 16:58 UTC by ptrdom

References https://github.com/scala-js/scala-js-dom/issues/622.

2021-11-10 17:00 UTC, ptrdom commented
I was unable to run `sbt prePR`, received this error:
```
[error] /scala-js-dom/readme/Index.scalatex:43:6: type mismatch;
[error]  found   : scalatex.site.Section.Proxy
[error]  required: scalatags.Text.all.Frag
[error]     (which expands to)  scalatags.generic.Frag[scalatags.text.Builder,String]
[error] @sect{scala-js-dom}
[error]      ^
[error] one error found
[error] (readme / Compile / compileIncremental) Compilation failed
```
It could be an issue with my environment - I am running Windows. WSL returned same errors.

2021-11-10 17:02 UTC, armanbilge commented
Hmm, looks like a problem with the README, I wonder if any of the code you changed touched that somehow. Let me try it as well.

2021-11-10 17:10 UTC, armanbilge commented
Ah, of course. The docs use `Fetch` which you just changed here right?
https://scala-js.github.io/scala-js-dom/#dom.Fetch

2021-11-10 17:11 UTC, armanbilge commented
You may want to check the code in here, see if there's something you need to update:
https://github.com/scala-js/scala-js-dom/blob/master/example/src/main/scala/example/Example.scala

2021-11-10 17:16 UTC, ptrdom commented
Yes, there is a change to `BodyInit` type - new member added to the union. Code of the example does not interact with the request body directly, not sure what should be changed there.

2021-11-10 17:18 UTC, ptrdom commented
CI does show some actual Firefox and Scala 3 errors, those I obviously can fix.

2021-11-10 17:22 UTC, armanbilge commented
Does `prePR` fail for you _before_ you make any changes? E.g. if you just it on `master`.

2021-11-10 20:14 UTC, armanbilge commented
Huh, with that same error message? Now that's definitely strange :)

2021-11-11 02:39 UTC, armanbilge requested changes

2021-11-11 02:39 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStream.scala
> +class ReadableStream[+T](
Unfortunately we cannot convert a `trait` to a class, this is binary incompatible :( I hope we can find a way to make this work even as a `trait`.

2021-11-11 15:20 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStream.scala
> +class ReadableStream[+T](
Converted it back to a `trait` and added construction in companion object's `apply` through `js.Dynamic`, is that fine?

2021-11-11 15:21 UTC, ptrdom commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
Scala 2.11 complains about this cast, I just could not figure out how to solve it, assistance needed 😬

2021-11-11 15:28 UTC, armanbilge commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
Hmm, try changing the cast to 
```suggestion
          }: js.UndefOr[js.Function1[ReadableStreamController[Tuna], js.UndefOr[Unit]]]
```

2021-11-11 15:32 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStream.scala
> +class ReadableStream[+T](
At a glance looks good 👍 thanks for making this work!

2021-11-11 15:34 UTC, armanbilge commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +  final def ReadableStreamTest: AsyncResult = async {
JSDom doesn't support `ReadableStream` yet so I don't think this can be a shared test.
- https://github.com/jsdom/jsdom/pull/3200

2021-11-11 15:57 UTC, ptrdom commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
Getting two errors with that cast:
```
\scala-js-dom\tests-shared\src\main\scala\org\scalajs\dom\tests\shared\SharedTests.scala:56:66: type mismatch;
[error]  found   : org.scalajs.dom.ReadableStreamController[Tuna] => Unit
[error]  required: scala.scalajs.js.UndefOr[scala.scalajs.js.Function1[org.scalajs.dom.ReadableStreamController[Tuna],scala.scalajs.js.UndefOr[Unit]]]
[error]     (which expands to)  scala.scalajs.js.|[scala.scalajs.js.Function1[org.scalajs.dom.ReadableStreamController[Tuna],scala.scalajs.js.|[Unit,Unit]],Unit]
[error]           start = { (controller: ReadableStreamController[Tuna]) =>
[error]                                                                  ^
```
```
\scala-js-dom\tests-shared\src\main\scala\org\scalajs\dom\tests\shared\SharedTests.scala:60:12: type mismatch;
[error]  found   : scala.scalajs.js.UndefOr[scala.scalajs.js.Function1[org.scalajs.dom.ReadableStreamController[Tuna],scala.scalajs.js.UndefOr[Unit]]]
[error]     (which expands to)  scala.scalajs.js.|[scala.scalajs.js.Function1[org.scalajs.dom.ReadableStreamController[Tuna],scala.scalajs.js.|[Unit,Unit]],Unit]
[error]  required: scala.scalajs.js.UndefOr[scala.scalajs.js.Function1[org.scalajs.dom.ReadableStreamController[Tuna],scala.scalajs.js.|[Unit,scala.scalajs.js.Promise[Unit]]]]
[error]     (which expands to)  scala.scalajs.js.|[scala.scalajs.js.Function1[org.scalajs.dom.ReadableStreamController[Tuna],scala.scalajs.js.|[Unit,scala.scalajs.js.Promise[Unit]]],Unit]
[error]           }: js.UndefOr[js.Function1[ReadableStreamController[Tuna], js.UndefOr[Unit]]]
[error]            ^
```

2021-11-11 16:02 UTC, ptrdom commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +  final def ReadableStreamTest: AsyncResult = async {
Where would you prefer this test to be moved? Could just create a new trait in shared module, but this test is not really shared. Could create a new module only with this test that chrome and firefox test modules will have as a dependency, but it could be considered an overkill.

2021-11-11 16:02 UTC, armanbilge commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
Hmm, I would just keep following the hints for what is "required" 😅

2021-11-11 16:09 UTC, armanbilge commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +  final def ReadableStreamTest: AsyncResult = async {
Yes, I vote for creating a new trait `BrowserTests` in shared. Hopefully JSDOM will catch up with `ReadableStream` support and it can eventually become a proper shared test.

2021-11-11 16:13 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +trait ReadableStreamController[-T] extends js.Object {
Oops, I think this is another one that can't change `class -> trait`. In general this change is not binary compatible.

2021-11-11 16:16 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: js.UndefOr[U]): js.Promise[U] = js.native
```suggestion
  def cancel[U](reason: js.UndefOr[U]): js.Promise[js.UndefOr[U]] = js.native
```

If the input is undefined, I assume the output can be as well?

2021-11-11 16:16 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +trait ReadableStreamController[-T] extends js.Object {
This change can be left out, I just wanted to remove it because this constructor is basically not provided and should not be called, as per spec.

2021-11-11 16:18 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamType.scala
> +sealed trait ReadableStreamType extends js.Any
For an example of how we are implementing `enum`s check the `scala-2` and `scala-3` specific source folders. This looks good for Scala 2 I think.

2021-11-11 16:19 UTC, ptrdom commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
I wonder how the compiler manages to get to `scala.scalajs.js.UndefOr[scala.scalajs.js.Function1[org.scalajs.dom.ReadableStreamController[Tuna],scala.scalajs.js.UndefOr[Unit]]]`, `scala.scalajs.js.UndefOr[Unit]` is basically `Unit | Unit`? This is an odd and very specific Scala 2.11 issue.

2021-11-11 16:21 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +trait ReadableStreamController[-T] extends js.Object {
Yeah, I regret not spending more time with this `ReadableStream` stuff before locking down the binary for 2.0.0. We'll have to fix these in 3.0.0 :(

I think you can just remove the constructor (maybe even make it `private`?) as a workaround.

2021-11-11 16:22 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: js.UndefOr[U]): js.Promise[U] = js.native
In that case:
```suggestion
  def cancel[U](reason: U): js.Promise[U] = js.native
```

2021-11-11 16:23 UTC, armanbilge commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
It is strange. I'll looking it in more detail later, if you can get everything else working until then that would be great 😁

2021-11-11 16:23 UTC, sjrd commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
Try wrapping the lambda with `js.defined(...)`. That should help the type inference.

2021-11-11 16:29 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: js.UndefOr[U]): js.Promise[U] = js.native
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader/cancel does show a call with no arguments passed - and my guess that is the most common usage - so should it be `def cancel[U](reason: js.UndefOr[U] = js.undefined): js.Promise[js.UndefOr[U]] = js.native` then?

2021-11-11 16:36 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: js.UndefOr[U]): js.Promise[U] = js.native
Although `reason: U` will not return `js.undefined`, so my suggestion is also not ideal.

2021-11-11 16:39 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: js.UndefOr[U]): js.Promise[U] = js.native
What if we just provide two overloads of this method?

```scala
def cancel[U](reason: U): js.Promise[U] = js.native
def cancel(): js.Promise[Unit] = js.native
```

2021-11-11 16:39 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +trait ReadableStreamController[-T] extends js.Object {
Make it `private[dom]`. That should do the trick.

2021-11-11 16:40 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: js.UndefOr[U]): js.Promise[U] = js.native
Consider using 2 overloads, then:
```scala
  def cancel[U](reason: U): js.Promise[U] = js.native
  def cancel(): js.Promise[Unit] = js.native
```

2021-11-11 16:41 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: js.UndefOr[U]): js.Promise[U] = js.native
I was a bit late to also reply with the same message 😄

2021-11-11 17:55 UTC, ptrdom commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
Tried these, still got errors:
```
start = js.defined({ (controller: ReadableStreamController[Tuna]) =>
  controller.enqueue(Tuna("blue"))
  controller.enqueue(Tuna("red"))
  controller.close()
}): js.UndefOr[js.Function1[ReadableStreamController[Tuna], Unit | js.Promise[Unit]]]
```
```
start = js.defined({ (controller: ReadableStreamController[Tuna]) =>
  controller.enqueue(Tuna("blue"))
  controller.enqueue(Tuna("red"))
  controller.close()
}: js.Function1[ReadableStreamController[Tuna], Unit | js.Promise[Unit]])
```
```
start = js.defined({ (controller: ReadableStreamController[Tuna]) =>
  controller.enqueue(Tuna("blue"))
  controller.enqueue(Tuna("red"))
  controller.close()
}: js.Function1[ReadableStreamController[Tuna], Unit])
```
```
start = js.defined({ (controller: ReadableStreamController[Tuna]) =>
  controller.enqueue(Tuna("blue"))
  controller.enqueue(Tuna("red"))
  controller.close()
}): js.UndefOr[js.Function1[ReadableStreamController[Tuna], Unit]]
```

2021-11-11 18:08 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +trait ReadableStreamController[-T] extends js.Object {
```
\scala-js-dom\dom\src\main\scala\org\scalajs\dom\ReadableStreamController.scala:18:36: Native JS classes may not have private constructors. Use `private[this]` to declare an internal constructor.
[error] class ReadableStreamController[-T] private[dom] (stream: ReadableStream[T] = null) extends js.Object {
```
What would be an ideal solution then?

2021-11-11 18:28 UTC, ptrdom commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
> +          }: js.Function1[ReadableStreamController[Tuna], Unit]
2.12 is okay with:
```
start = js.defined({ (controller: ReadableStreamController[Tuna]) =>
  controller.enqueue(Tuna("blue"))
  controller.enqueue(Tuna("red"))
  controller.close()
}): js.UndefOr[js.Function1[ReadableStreamController[Tuna], Unit | js.Promise[Unit]]]
```
But 2.11 does not accept anything 😞

2021-11-11 20:20 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +trait ReadableStreamController[-T] extends js.Object {
Try `private[this]`, as suggested.

2021-11-11 21:25 UTC, ptrdom commented
I think the only issue left now is the very first one - https://github.com/scala-js/scala-js-dom/pull/628#issuecomment-965546913.

2021-11-11 21:39 UTC, ptrdom commented
And it was a Windows related issue. Big thanks to Microsoft for WSL 👏

2021-11-11 21:50 UTC, armanbilge commented
Nice work getting it green! 🎉

2021-11-12 03:18 UTC, armanbilge reviewed
This is a _very_ complex API, so thank you for all your efforts and apologies if I'm confused about something in the comments!

2021-11-12 03:18 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamQueuingStrategy.scala
> +  var size: js.Function1[Chunk[T], Unit]
```suggestion
  var size: js.Function1[T, Int]
```

Right?

2021-11-12 03:18 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamUnderlyingSource.scala
> +  var start: js.UndefOr[js.Function1[ReadableStreamController[T], Unit | js.Promise[Unit]]] = js.undefined
```suggestion
  var start: js.UndefOr[js.Function1[ReadableStreamController[T], js.UndefOr[js.Promise[Unit]]]] = js.undefined
```

They are aliases.

2021-11-12 03:18 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamUnderlyingSource.scala
> +  var pull: js.UndefOr[js.Function1[ReadableStreamController[T], Unit | js.Promise[Unit]]] = js.undefined
`js.UndefOr` here, like above.

2021-11-12 03:18 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamUnderlyingSource.scala
> +  var cancel: js.UndefOr[js.Function1[js.Any, Unit | js.Promise[Unit]]] = js.undefined
`js.UndefOr` here, like above.

2021-11-12 03:18 UTC, armanbilge commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/BrowserTests.scala
> +    )
![One_Fish_Two_Fish_Red_Fish_Blue_Fish_(cover_art)](https://user-images.githubusercontent.com/3119428/141403050-36ffeb47-e3ef-457d-8121-6a7d4117b4f9.jpg)

2021-11-12 11:18 UTC, ptrdom commented
@armanbilge Thank you for the review! I think I have addressed all of your comments.

2021-11-12 14:16 UTC, armanbilge reviewed
Sorry, just a few more things I noticed on this pass!

Let's get another pair of eyes, whenever you have a chance @sjrd or @japgolly, much appreciated! :)

2021-11-12 14:16 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel(): js.Promise[Unit] = js.native
Sorry to fiddle with this again :( I think the return type should just be `js.Promise[Unit]`, at least according to this:
https://streams.spec.whatwg.org/#generic-reader-mixin-definition

The problem is that MDN is inconsistent and suggests an API like what we have currently. I think it's probably better to stick to the spec, also a `Unit` return type is less likely to get users into trouble 😅 
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader/cancel

Also I think we need to fix `closed` above.

2021-11-12 14:16 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamUnderlyingSource.scala
> +  var autoAllocateChunkSize: js.UndefOr[Double] = js.undefined
Maybe make this an `Int` too?

2021-11-12 14:16 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel(): js.Promise[Unit] = js.native
Aha, maybe it's not inconsistent. The MDN docs are for `ReadableStreamDefaultReader`, but the spec is for the `ReadableStreamGenericReader` like what we have here. So we should definitely follow the spec here, sorry!

2021-11-12 14:40 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +  def enqueue(chunk: T): js.UndefOr[Int] = js.native
What is the purpose of having `chunk: js.UndefOr[T]`? If there would be a `ReadableStream[Unit]`, then `T` could just be `Unit`. If it is anything but a `Unit`, I could not find anywhere that it should be possible to pass a `Unit`.

2021-11-12 15:06 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +  def enqueue(chunk: T): js.UndefOr[Int] = js.native
That's a good question. I'm just going by the definition in the spec, which suggests it can be optional:
https://streams.spec.whatwg.org/#rs-default-controller-class-definition
```idl
interface ReadableStreamDefaultController {
  readonly attribute unrestricted double? desiredSize;

  undefined close();
  undefined enqueue(optional any chunk);
  undefined error(optional any e);
};
```

2021-11-12 15:19 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +  def enqueue(chunk: T): js.UndefOr[Int] = js.native
This change does produce an error Scala 2.11 - `contravariant type T occurs in invariant position in type scala.scalajs.js.UndefOr[T] of value chunk`. Is contravariance needed in `ReadableStreamController`?

2021-11-12 15:24 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamController.scala
> +  def enqueue(chunk: T): js.UndefOr[Int] = js.native
Not again 😅  we can do the overload trick again here instead.

2021-11-14 19:47 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel(): js.Promise[Unit] = js.native
I wrote a test for this one, neither of browsers return a `js.Promise` with given reason.

2021-11-14 20:51 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel(): js.Promise[Unit] = js.native
Thanks for looking into this! Much appreciated. I guess MDN is just wrong ...

2021-11-14 20:54 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel(): js.Promise[Unit] = js.native
It did sound weird to me when I read it, kind of a pointless loop through of a value.

2021-11-14 20:56 UTC, armanbilge reviewed
This looks great, thanks for all your efforts! Just one last tiny thing 😅

2021-11-14 20:56 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: U): js.Promise[Unit] = js.native
We no longer need the type parameter :)

```suggestion
  def cancel(reason: Any): js.Promise[Unit] = js.native
```

2021-11-14 20:56 UTC, armanbilge commented on tests-shared/src/main/scala/org/scalajs/dom/tests/shared/BrowserTests.scala
> +  final def ReadableStreamReaderCancelPromiseTest: AsyncResult = async {
👍

2021-11-14 21:00 UTC, ptrdom commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: U): js.Promise[Unit] = js.native
Ah, committing the suggestion will not be enough, need to regenerate `api-reports` 😞

2021-11-14 21:02 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStreamReader.scala
> +  def cancel[U](reason: U): js.Promise[Unit] = js.native
Sorry about that :( we'd like to phase out the API reports b/c it's frustrating for contributors, we have a plan in https://github.com/scala-js/scala-js-dom/issues/503.

2021-11-14 21:07 UTC, armanbilge approved these changes

2021-11-15 10:39 UTC, sjrd requested changes

2021-11-15 10:39 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/ReadableStream.scala
> +      .asInstanceOf[ReadableStream[T]]
I'm afraid this is plain incorrect. It won't create a valid `ReadableStream`, since the result won't be an `instanceof ReadableStream`. It also won't have all the methods that `ReadableStream` is supposed to have.

Since it is a class, it really need to be instantiated with `new`. You could achieve that with `js.Dynamic.newInstance`, but I don't think that is the best choice here, as it will (re-)create a precedent for `apply` methods that actually create stuff.

Instead, I think the best path forward is:
1. Define a `class ReadableStreamClass` that extends `ReadableStream` and provides the correct constructor.
2. Add a self-type to `ReadableStream` that it must be a `ReadableStreamClass`.
3. Document that `ReadableStream` should be created through `ReadableStreamClass`, but other remain typed everywhere as `ReadableStream` (for historical/compatibility reasons).

Concretely, it would look like this:
```scala
/** defined at [[https://streams.spec.whatwg.org/#readable-stream ¶2.1. Readable Streams]] of whatwg Streams spec.
  *
  * For historical reasons, ReadableStream is a trait rather than a class.
  * In order to instantiate it, use `new ReadableStreamClass(...)`.
  * Prefer `ReadableStream` in typings everywhere else, notably in
  * method signatures.
  *
  * @tparam T
  *   Type of the Chunks returned by the Stream. Can't make it coveriant, due to T
  */
@js.native
trait ReadableStream[+T] extends js.Object { this: ReadableStreamClass =>
  ...
}

@js.native
@JSGlobal("ReadableStream")
class ReadableStreamClass(underlyingSource: ..., queueingStrategy: ...)
    extends ReadableStream
```
When you get to scalajs-dom v3, you can turn `ReadableStream` into a class, and make `ReadableStreamClass` an `@deprecated type` alias of `ReadableStream`.

2021-11-15 13:18 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ReadableStream.scala
> +      .asInstanceOf[ReadableStream[T]]
Hum, I'm not sure I agree. Would you mind expanding more on this point?

> I don't think that is the best choice here, as it will (re-)create a precedent for apply methods that actually create stuff.

We all agree we want to avoid this precedent ... but is this a precedent for users, or a precedent for maintainers, or both/something else?

My concern is about discovery: it's much more intuitive to look to the `apply` method in the companion object then for a differently-named class.

Furthermore, _if_ scala-js-dom v3 ever happens (😅) by that time we will hopefully be in a Scala 3+ world where _all_ classes can be created without the `new` keyword anyway! So we could make this change source-compatibly I think?

2021-11-15 13:32 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/ReadableStream.scala
> +      .asInstanceOf[ReadableStream[T]]
Hum, perhaps you're right. I guess we can leave it as is, then.

2021-11-15 13:32 UTC, sjrd approved these changes

2021-11-15 13:32 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/ReadableStream.scala
> +      .newInstance(js.Dynamic.global.selectDynamic("ReadableStream"))(
```suggestion
      .newInstance(js.Dynamic.global.ReadableStream)(
```

2021-11-17 12:23 UTC, merged

2021-11-17 12:30 UTC, armanbilge commented
@ptrdom thanks again for this fantastic contribution! It is now published as `2.0.0+25-ed28f246-SNAPSHOT`.

2021-12-26 10:22 UTC, julienrf commented
Hello! Do you plan to cut a release with this changes soon?

2021-12-26 17:09 UTC, armanbilge commented
@julienrf hello :) Out of curiosity, is this blocking something? Although the API facaded here is described in the spec, it's basically unsupported in browsers at this time.
https://caniuse.com/mdn-api_request_request_readablestream_request_body

Otherwise, personally I'm 👍 to a release :) Since we've added new APIs, the next release will be 2.1.0 in which we also need to fix https://github.com/scala-js/scala-js-dom/issues/624. So it will take a little time to get it ready.

2021-12-26 17:30 UTC, julienrf commented
It is not just about the change to the Fetch facade, the PR contains other changes related to the `ReadableStream` API. As far as I understand, those changes are currently supported by the browsers: https://caniuse.com/?search=readablestream

This is not really blocking us since we can always define the facade we want outside of scala-js-dom, but it would be simpler to just use the one of scala-js-dom. Our related PR is https://github.com/endpoints4s/endpoints4s/pull/972

2021-12-26 17:41 UTC, armanbilge commented
Ah, that's right, you want to use this as your stream implementation :) thanks for the reply. I'll start getting a release together.

2021-12-31 05:52 UTC, armanbilge commented
@julienrf I just released [v2.1.0](https://github.com/scala-js/scala-js-dom/releases/tag/v2.1.0). @ptrdom thank you again for this fantastic contribution, also looks like you've been doing great work in endpoints4s :)

2022-01-03 07:40 UTC, julienrf commented
Thank you!