Fix `dom.crypto.getRandomValues`
scala-js/scala-js-dom pull request #669
Opened 2022-01-12 22:43 UTC by armanbilge

Will fix #668.

2022-01-12 22:48 UTC, armanbilge commented
For df03142 I get the following in CI:
```
[error] Test org.scalajs.dom.tests.chrome.ChromeTests.cryptoGetRandomValues failed: scala.scalajs.js.JavaScriptException: TypeError: Illegal invocation, took 0.000300001 sec
[error]     at org.scalajs.dom.tests.shared.BrowserTests$class.cryptoGetRandomValues(file:///home/runner/work/scala-js-dom/scala-js-dom/tests-chrome/target/scala-2.11/testschrome-test-fastopt/main.js:3106)

[error] Test org.scalajs.dom.tests.firefox.FirefoxTests.cryptoGetRandomValues failed: scala.scalajs.js.JavaScriptException: TypeError: 'getRandomValues' called on an object that does not implement interface Crypto., took 0 sec
[error]     at org.scalajs.dom.tests.shared.BrowserTests$class.cryptoGetRandomValues(file:///home/runner/work/scala-js-dom/scala-js-dom/tests-firefox/target/scala-2.11/testsfirefox-test-fastopt/main.js:3106)
```

2022-01-12 23:08 UTC, sjrd requested changes

2022-01-12 23:08 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/crypto/package.scala
> +    webcrypto.getRandomValues(array)
That's not a binary compatible change. An `@js.native` thing must remain `@js.native`, and non-native thing must remain non-native.

2022-01-12 23:09 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/crypto/package.scala
> +    webcrypto.getRandomValues(array)
Ah, thanks, I wanted to ask you about that.

Then, I'm not sure if this is possible to fix at all. Do you have any suggestions?

2022-01-12 23:11 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/crypto/package.scala
> +    webcrypto.getRandomValues(array)
Not right now. I'm about to go to sleep.

But what is *actually* the issue in the first place? Why doesn't the `@JSGlobal` work?

2022-01-12 23:12 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/crypto/package.scala
> +    webcrypto.getRandomValues(array)
No worries, look when you have a chance and get well soon :)

I posted the error in https://github.com/scala-js/scala-js-dom/pull/669#issuecomment-1011519586.

2022-01-17 20:48 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/crypto/package.scala
> +    webcrypto.getRandomValues(array)
Anyone have any ideas for this one?

2022-01-18 02:18 UTC, japgolly commented on dom/src/main/scala/org/scalajs/dom/crypto/package.scala
> +    webcrypto.getRandomValues(array)
A binary-incompatible workaround would require a release of 3.0.0 right? I think the only option is to fix what looks to be a bug in Scala.js.

2022-01-19 17:45 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/crypto/package.scala
> +    webcrypto.getRandomValues(array)
Super ugly, but when the situation is desperate, one can always rely on the good old `protected[package]` trick:
```scala
  // for binary compat; unusable
  @JSGlobal("crypto.getRandomValues")
  @js.native
  protected[crypto] def getRandomValues(array: ArrayBufferView): ArrayBufferView = js.native

  @inline
  def getRandomValues(array: ArrayBufferView)(implicit dummy: DummyImplicit): ArrayBufferView =
    webcrypto.getRandomValues(array)
```

2022-01-19 18:51 UTC, armanbilge commented
I assume that releasing this fix will require a bump to 2.2.0?

2022-01-19 19:33 UTC, sjrd approved these changes

2022-01-19 19:42 UTC, merged

2022-01-20 00:09 UTC, armanbilge commented
After reading https://github.com/scalacenter/sbt-version-policy/issues/71 I understand forward binary compatibility is really just an approximation used for checking backward source compatibility. So even though we are breaking forward binary compatibility here, we are not breaking source compatibility, so we can release this in 2.1.1.

2022-01-20 04:30 UTC, sjrd commented
You're changing the public API (even if it's just an "added" implicit parameter) so you are potentially breaking source compatibility.

In fact, given the nature of scalajs-dom, it is extremely unlikely that there will *ever* be a patch release. It's virtually 100% API and no implementation, so any change triggers a minor version update.

2022-01-20 04:35 UTC, armanbilge commented
Thanks, that's very helpful.