Add WorkerOptions to [Shared]Worker constructors
scala-js/scala-js-dom pull request #691
Opened 2022-04-06 17:12 UTC by armanbilge

https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker/SharedWorker

2022-04-06 17:13 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/SharedWorker.scala
> +class SharedWorker(scriptURL: String, options: js.UndefOr[String | WorkerOptions] = js.native) extends AbstractWorker {
I wasn't quite sure the best thing to do here. The other option I guess is to have two separate constructors.

2022-04-06 17:14 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/SharedWorker.scala
>    * @param stringUrl
```suggestion
  * @param scriptURL
```

2022-04-07 04:03 UTC, sjrd requested changes

2022-04-07 04:03 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/WorkerOptions.scala
> +@js.native
This should be non-native, and have `= js.undefined` fields.

2022-04-07 04:03 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/Worker.scala
> +class Worker(scriptURL: String, options: js.UndefOr[WorkerOptions] = js.native) extends AbstractWorker {
An overload would provide better inference here, I think. It may allow to use the `new { ... }` idiom in Scala 3.

2022-04-07 13:57 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/WorkerOptions.scala
> +@js.native
Woops, I botched that :)

2022-04-07 13:58 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/Worker.scala
> +class Worker(scriptURL: String, options: js.UndefOr[WorkerOptions] = js.native) extends AbstractWorker {
Ah, good point about the `new { ... }`. Is it worth to do something similar for `SharedWorker` as well?

2022-04-07 14:34 UTC, sjrd commented on dom/src/main/scala/org/scalajs/dom/SharedWorker.scala
> +  def this(scriptURL: String, options: WorkerOptions) = this(scriptURL, js.defined(options))
That works, but you're making it hard on yourself. The following is simpler:
```suggestion
class SharedWorker(scriptURL: String) extends AbstractWorker {
  def this(scriptURL: String, name: String) = this(scriptURL)

  def this(scriptURL: String, options: WorkerOptions) = this(scriptURL)
```
Note that actual arguments in the `= this(...)` call are always ignored. We just need to make the typechecker happy, but they will never be used.

2022-04-07 14:39 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/SharedWorker.scala
> +  def this(scriptURL: String, options: WorkerOptions) = this(scriptURL, js.defined(options))
Ah, I didn't know that :) this is much nicer. That makes sense.

2022-04-07 14:46 UTC, sjrd approved these changes

2022-04-13 17:10 UTC, merged