Add `InputEvent`, `StaticRange`, `AbstractRange`
scala-js/scala-js-dom pull request #695
Opened 2022-04-16 15:26 UTC by armanbilge

Just wanted to add `InputEvent` and it sort of snowballed :)

- https://developer.mozilla.org/en-US/docs/Web/API/AbstractRange
- https://developer.mozilla.org/en-US/docs/Web/API/StaticRange
- https://developer.mozilla.org/en-US/docs/Web/API/InputEvent
- https://www.w3.org/TR/input-events-2/#interface-InputEvent-Attributes

2022-04-16 15:28 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/StaticRangeInit.scala
> +}
This is an unusual init, since none of the parameters are optional.

2022-04-30 19:56 UTC, armanbilge commented
After we land this one I'm hoping we can cut a v2.2.0, now that we've accumulated a handful of contributor PRs :)

2022-05-06 15:15 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/InputEventInit.scala
> +  var ranges: js.UndefOr[js.Array[StaticRange]]
```suggestion
  var ranges: js.UndefOr[js.Array[StaticRange]] = js.undefined
```

2022-05-06 16:15 UTC, armanbilge commented
Polite ping @japgolly :) if you don't have time to review for a while, no big deal, just let me know and I won't block v2.2.0 on this if that's okay with you!

2022-05-24 02:58 UTC, japgolly commented
> Polite ping @japgolly :) if you don't have time to review for a while, no big deal, just let me know and I won't block v2.2.0 on this if that's okay with you!

Oh my! Apologies @armanbilge ! I haven't been keeping up with my email lately so I missed this. I'll get to this very son

2022-05-24 22:44 UTC, armanbilge commented
No worries, whenever you get to it! I hope you don't mind I released v2.2.0, it was really wonderful to get a bunch of contributions and I wanted to get it out :)

2022-05-29 23:35 UTC, japgolly requested changes

2022-05-29 23:35 UTC, japgolly commented on dom/src/main/scala/org/scalajs/dom/InputEventInit.scala
> +  var dataTransfer: js.UndefOr[DataTransfer] = js.undefined
`dataTransfer` not allowed here

2022-05-29 23:35 UTC, japgolly commented on dom/src/main/scala/org/scalajs/dom/InputEventInit.scala
> +  var ranges: js.UndefOr[js.Array[StaticRange]] = js.undefined
`ranges` not allowed here

2022-05-29 23:35 UTC, japgolly commented on dom/src/main/scala/org/scalajs/dom/StaticRange.scala
> +package org.scalajs.dom
unnecessary (and false) package comment

2022-05-29 23:35 UTC, japgolly commented on dom/src/main/scala/org/scalajs/dom/StaticRangeInit.scala
> +}
Should we provide `object StaticRangeInit { def apply(...) = ... }` too?

2022-05-29 23:46 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/StaticRangeInit.scala
> +}
Good question. Seems reasonable, but I'm not sure if it's consistent with our style. I haven't gone through them carefully, but I think some of the crypto init-style objects may be a mix of required and optional parameters. Should we add `apply` methods for those too?

2022-05-30 02:26 UTC, japgolly commented on dom/src/main/scala/org/scalajs/dom/StaticRangeInit.scala
> +}
Ah, good point. I'll leave that question open and consider it out of scope for this PR then.

2022-05-30 02:27 UTC, japgolly approved these changes
LGTM. Thanks for the follow-up PR and your patience :smile:

2022-05-30 10:17 UTC, merged