Add `hasPointerCapture/releasePointerCapture/setPointerCapture` to `Element`
scala-js/scala-js-dom pull request #822
Opened 2023-11-15 10:53 UTC by updraft0

Looks like these were missing from the `Element` facade:

* https://developer.mozilla.org/en-US/docs/Web/API/Element/hasPointerCapture
* https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture
* https://developer.mozilla.org/en-US/docs/Web/API/Element/releasePointerCapture

2023-11-15 16:26 UTC, zetashift requested changes

2023-11-15 16:26 UTC, zetashift commented on dom/src/main/scala/org/scalajs/dom/Element.scala
> +  def releasePointerCapture(pointerId: Double): Boolean = js.native
```suggestion
  def releasePointerCapture(pointerId: Double): Unit = js.native
```
According to the spec `releasePointerCapture` returns undefined: https://w3c.github.io/pointerevents/#dom-element-releasepointercapture

2023-11-15 22:10 UTC, updraft0 commented on dom/src/main/scala/org/scalajs/dom/Element.scala
> +  def releasePointerCapture(pointerId: Double): Boolean = js.native
So it does, fixed

2023-11-21 18:46 UTC, zetashift approved these changes

2023-11-21 18:46 UTC, zetashift commented
Thank you! :D

2023-12-21 20:21 UTC, merged