Added missing constructors to ImageData facade.
scala-js/scala-js-dom pull request #829
Opened 2024-01-12 16:52 UTC by dragonfly-ai

The ImageData spec references several constructors that scala-js-dom has omitted:

https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData

This PR means to include these features.

2024-01-12 17:13 UTC, dragonfly-ai commented
Should we introduce an ImageSettings class?

The JS docs just supply them with anonymous argiments:

```javascript

let imageData = new ImageData(200, 100, { colorSpace: "display-p3" });

```

2024-01-12 17:31 UTC, armanbilge commented
> Should we introduce an ImageSettings class?

Yes. Here's an example of how it should be defined.

https://github.com/scala-js/scala-js-dom/blob/efe1b87772b114c95a3d30fcdddc603f0ebb0b23/dom/src/main/scala/org/scalajs/dom/DOMRectInit.scala

2024-01-12 17:33 UTC, dragonfly-ai commented
OK, I'll try to add that, too.

2024-01-12 18:27 UTC, dragonfly-ai commented
> Yes. Here's an example of how it should be defined.

Should we also have a companion object with the two supported values?

"colorSpace: Specifies the color space of the image data. Can be set to `"srgb"` ... or `"display-p3"` ..."

```scala
object ImageSettings {
  val sRGB:String = "srgb"
  val DisplayP3:String = "display-p3"
}
```

2024-01-12 18:40 UTC, dragonfly-ai commented
What about adding a companion object to `ImageSettings` since its only field supports exactly two values: "srgb" and "display-p3"?

2024-03-04 16:38 UTC, zetashift commented
> What about adding a companion object to ImageSettings since its only field supports exactly two values: "srgb" and "display-p3"?

Wouldn't these be better off as an `enum` then? E.g. `ImageSettingsColorSpace`?
@dragonfly-ai This PR LGTM, if you want to add the enum or not, let me know, it can always be a separate ticket/PR

2024-03-04 16:38 UTC, zetashift approved these changes

2024-03-07 20:30 UTC, dragonfly-ai commented
Thanks for approving!
I've never tried passing a Scala enum to a native JS function; do Scala enumerations interoperate well with plain JavaScript?

2024-03-07 22:44 UTC, sjrd commented
No, they don't.

2024-03-08 05:01 UTC, dragonfly-ai commented
Well, in that case, companion object with constants for `display-p3` and `srgb`, or should we just leave it out?

2024-03-18 13:52 UTC, dragonfly-ai commented
Added the `ImageSettings` object as discussed.

2024-03-19 03:21 UTC, zetashift requested changes

2024-03-19 03:21 UTC, zetashift commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +}
Enums are done a bit differently to support Scala 2 and Scala 3. You'll need 2 files, one in `scala-2` and one in `scala-3

For example the `CompressionFormat` enum is made like this:
Scala 3: https://github.com/scala-js/scala-js-dom/blob/efe1b87772b114c95a3d30fcdddc603f0ebb0b23/dom/src/main/scala-3/org/scalajs/dom/CompressionFormat.scala#L5-L13
Scala 2: https://github.com/scala-js/scala-js-dom/blob/efe1b87772b114c95a3d30fcdddc603f0ebb0b23/dom/src/main/scala-2/org/scalajs/dom/CompressionFormat.scala#L5-L14

2024-03-20 12:26 UTC, armanbilge requested changes

2024-03-20 12:26 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
1. This should be called [`ImageDataSettings`](https://html.spec.whatwg.org/multipage/canvas.html#imagedatasettings)
2. Remove the companion object
3. As @zetashift points out we should add an enum [`PredefinedColorSpace`](https://html.spec.whatwg.org/multipage/canvas.html#predefinedcolorspace)

2024-03-20 16:00 UTC, dragonfly-ai commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
I've tried to do all of these things, but can't get the enum to work.

Can you see the problem?
https://scastie.scala-lang.org/C3O0MaFoQpW8dhGT7QIJDw

2024-03-20 17:58 UTC, dragonfly-ai commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
I would like to also add this test, but can't figure out where to put it:

```scala

  @Test
  final def ImageDataTest(): Unit = {
    import org.scalajs.dom.{ImageData, ImageDataSettings, PredefinedColorSpace}
    import PredefinedColorSpace._

    val defaultImageData: ImageData = new ImageData(200, 100, new ImageDataSettings { colorSpace = `display-p3` })
    assertEquals(defaultImageData.width, 200)
    assertEquals(defaultImageData.height, 100)
  }
  ```

2024-03-20 18:15 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
> I've tried to do all of these things, but can't get the enum to work with string literals.

Can you push the code and I'll review it? Thanks :)



> I would like to also add this test, but can't figure out where to put it:

How about here?

https://github.com/scala-js/scala-js-dom/blob/009226a920c4bca457ef8c5c8a57c0f1283c193d/tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala

2024-03-20 18:20 UTC, dragonfly-ai commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
I tried that first, but `ImageData` isn't defined in node.

`[error] Test org.scalajs.dom.tests.node.jsdom.NodeJsdomTests.ImageDataTest failed: scala.scalajs.js.JavaScriptException: ReferenceError: ImageData is not defined, took 0.000862245 sec`

Maybe it ought to be?  (I sure would like to have it there.)

2024-03-20 18:20 UTC, dragonfly-ai commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
pushed!  ready for review.

2024-03-20 18:22 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
> I tried that first, but `ImageData` isn't defined in node.

I see, that's too bad. In that case move it to the `BrowserTests` file.

2024-03-20 18:47 UTC, dragonfly-ai commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
Awesome!  Adding that test may have exposed a bug in Firefox:

![image](https://github.com/scala-js/scala-js-dom/assets/24378760/03174164-b52c-4e7e-94e6-6f76b562a027)

2024-03-20 19:20 UTC, dragonfly-ai commented on dom/src/main/scala/org/scalajs/dom/ImageSettings.scala
> +object ImageSettings {
all of the other constructors seem to work, so I'll write tests for all of those and comment this one out.

2024-03-21 16:18 UTC, armanbilge approved these changes
nice work, thanks!

2024-03-21 16:19 UTC, merged