Add composition related handlers and field
scala-js/scala-js-dom pull request #839
Opened 2024-03-12 01:52 UTC by nineclue

Keyboard Event is missing isComposing field.
HTMLElment is missing composition related event handlers.

Both are listed in MDN documents. 
This is my first pull request. Hope it is correct.

2024-03-19 23:41 UTC, armanbilge requested changes

2024-03-19 23:41 UTC, armanbilge commented on dom/src/main/scala/org/scalajs/dom/HTMLElement.scala
Thanks for the PR. If I understand correctly, these APIs should be added to `Element`, not `HTMLElement`.

https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event

2024-03-20 05:14 UTC, nineclue commented on dom/src/main/scala/org/scalajs/dom/HTMLElement.scala
You're correct.  Moved handlers to Element.
Thanks for pointing out.

2024-03-20 12:21 UTC, armanbilge approved these changes
Excellent, thank you!

2024-03-20 12:22 UTC, merged